// DO NOT EDIT. This is code generated via package:easy_localization/generate.dart

// ignore_for_file: prefer_single_quotes, avoid_renaming_method_parameters, constant_identifier_names

import 'dart:ui';

import 'package:easy_localization/easy_localization.dart' show AssetLoader;

class CodegenLoader extends AssetLoader{
  const CodegenLoader();

  @override
  Future<Map<String, dynamic>?> load(String path, Locale locale) {
    return Future.value(mapLocales[locale.toString()]);
  }

  static const Map<String,dynamic> _de = {
  "recipe": "Rezept",
  "my_recipe_book": "Mein Rezeptbuch",
  "recipe_book": "Rezeptbuch",
  "recipe_title": "Name des Rezepts",
  "new_recipe": "Neues Rezept",
  "add_new_recipe": "Neues Rezept hinzufügen",
  "no_recipe_add_yet": "Noch kein Rezept hinzugefügt...",
  "ingredients": "Zutaten",
  "ingredient": {
    "full": "{quantity} {measure} {name}",
    "partial": "{quantity} {fraction} {measure} {name}"
  },
  "add_ingredient": "Zutat hinzufügen",
  "delete_ingredient": "Zutat löschen",
  "move_ingredient": "Zutat verschieben",
  "ingredient_hint": "z.B.: 100g Zucker",
  "steps": "Zubereitung",
  "add_step": "Schritt hinzufügen",
  "delete_step": "Schritt löschen",
  "move_step": "Schritt verschieben",
  "title_required": "Bitte geben Sie einen Titel ein",
  "type": "Typ",
  "type_required": "Bitte wählen Sie einen Typ",
  "serve": "Portionen",
  "description": "Beschreibung",
  "peoples_serves": "Portionen für wie viele Personen",
  "person": {
    "person": "Person",
    "people": "Personen"
  },
  "difficulty_level": "Schwierigkeit",
  "difficulty_required": "Bitte wählen Sie ein Niveau",
  "difficulty": {
    "easy": "einfach",
    "medium": "mittel",
    "hard": "schwer"
  },
  "recipe_type": {
    "breakfast": "Frühstück",
    "meal": "Mahlzeit",
    "side": "Beilage",
    "snack": "Snack",
    "drink": "Getränk",
    "dessert": "Dessert",
    "some_other": "Sonstiges"
  },
  "attention": "Achtung",
  "about": "Über",
  "backup": "Sicherung",
  "wish_leave": "Möchten Sie ohne Speichern verlassen?",
  "sure_delete": "Sind Sie sicher, dass Sie dieses Rezept löschen möchten?",
  "stay": "Bleiben",
  "exit": "Verlassen",
  "yes": "Ja",
  "no": "Nein",
  "unknow": "unbekannt",
  "not_informed": "nicht angegeben",
  "undefined": "undefiniert",
  "save": "Speichern",
  "edit": "Bearbeiten",
  "delete": "Löschen",
  "search": "Rezepte suchen...",
  "favorites": "Favoriten",
  "no_favorites_yet": "Noch keine Lieblingsrezepte.\nTippen Sie auf das Herzsymbol, um eines hinzuzufügen!",
  "no_results_found": "Keine Rezepte für diese Suche gefunden.",
  "sort_by": "Sortieren nach",
  "sort_by_name": "Name",
  "sort_by_type": "Typ",
  "sort_by_difficulty": "Schwierigkeit",
  "prep_time": "Zubereitungszeit",
  "prep_time_minutes": "{minutes} Min.",
  "prep_time_hint": "Zeit in Minuten",
  "about_app_info": "App-Informationen",
  "about_version": "Version",
  "about_build": "Build",
  "about_package": "Paket",
  "about_device_info": "Geräteinformationen",
  "about_device_model": "Modell",
  "about_device_os": "Betriebssystem",
  "about_device_os_version": "BS-Version",
  "about_licenses": "Open-Source-Lizenzen",
  "settings": "Einstellungen",
  "settings_theme_color": "Themenfarbe",
  "settings_language": "Sprache"
};
static const Map<String,dynamic> _ru = {
  "recipe": "Рецепт",
  "my_recipe_book": "Моя книга рецептов",
  "recipe_book": "Книга рецептов",
  "recipe_title": "Название рецепта",
  "new_recipe": "Новый рецепт",
  "add_new_recipe": "Добавить новый рецепт",
  "no_recipe_add_yet": "Рецептов пока нет...",
  "ingredients": "Ингредиенты",
  "ingredient": {
    "full": "{quantity} {measure} {name}",
    "partial": "{quantity} {fraction} {measure} {name}"
  },
  "add_ingredient": "Добавить ингредиент",
  "delete_ingredient": "Удалить ингредиент",
  "move_ingredient": "Переместить ингредиент",
  "ingredient_hint": "напр.: 100г сахара",
  "steps": "Приготовление",
  "add_step": "Добавить шаг",
  "delete_step": "Удалить шаг",
  "move_step": "Переместить шаг",
  "title_required": "Пожалуйста, введите название",
  "type": "Тип",
  "type_required": "Пожалуйста, выберите тип",
  "serve": "Порции",
  "description": "Описание",
  "peoples_serves": "Порций на сколько человек",
  "person": {
    "person": "человек",
    "people": "человек"
  },
  "difficulty_level": "Сложность",
  "difficulty_required": "Пожалуйста, выберите уровень",
  "difficulty": {
    "easy": "лёгкий",
    "medium": "средний",
    "hard": "сложный"
  },
  "recipe_type": {
    "breakfast": "завтрак",
    "meal": "основное блюдо",
    "side": "гарнир",
    "snack": "перекус",
    "drink": "напиток",
    "dessert": "десерт",
    "some_other": "другое"
  },
  "attention": "Внимание",
  "about": "О приложении",
  "backup": "Резервная копия",
  "wish_leave": "Хотите выйти без сохранения?",
  "sure_delete": "Вы уверены, что хотите удалить этот рецепт?",
  "stay": "Остаться",
  "exit": "Выйти",
  "yes": "Да",
  "no": "Нет",
  "unknow": "неизвестно",
  "not_informed": "не указано",
  "undefined": "не определено",
  "save": "Сохранить",
  "edit": "Редактировать",
  "delete": "Удалить",
  "search": "Поиск рецептов...",
  "favorites": "Избранное",
  "no_favorites_yet": "Избранных рецептов пока нет.\nНажмите на значок сердца, чтобы добавить!",
  "no_results_found": "Рецепты по этому запросу не найдены.",
  "sort_by": "Сортировать по",
  "sort_by_name": "Название",
  "sort_by_type": "Тип",
  "sort_by_difficulty": "Сложность",
  "prep_time": "Время приготовления",
  "prep_time_minutes": "{minutes} мин.",
  "prep_time_hint": "Время в минутах",
  "about_app_info": "Информация о приложении",
  "about_version": "Версия",
  "about_build": "Сборка",
  "about_package": "Пакет",
  "about_device_info": "Информация об устройстве",
  "about_device_model": "Модель",
  "about_device_os": "Операционная система",
  "about_device_os_version": "Версия ОС",
  "about_licenses": "Лицензии открытого кода",
  "settings": "Настройки",
  "settings_theme_color": "Цвет темы",
  "settings_language": "Язык"
};
static const Map<String,dynamic> _pt = {
  "recipe": "Receita",
  "my_recipe_book": "Meu livro de receitas",
  "recipe_book": "Livro de receitas",
  "recipe_title": "Nome da receita",
  "new_recipe": "Nova receita",
  "add_new_recipe": "Adicionar nova receita",
  "no_recipe_add_yet": "Nenhuma receita adiciona ainda...",
  "ingredients": "Ingredientes",
  "ingredient": {
    "full": "{quantity} {measure} de {name}",
    "partial": "{quantity} {fraction} {measure} de {name}"
  },
  "add_ingredient": "Adicionar ingrediente",
  "delete_ingredient": "Excluir ingrediente",
  "move_ingredient": "Mover ingrediente",
  "ingredient_hint": "ex.: 100g de açúcar",
  "steps": "Modo de preparo",
  "add_step": "Adicionar passo",
  "delete_step": "Excluir passo",
  "move_step": "Mover passo",
  "title_required": "Por favor, informe um título",
  "type": "Tipo",
  "type_required": "Por favor, selecione um tipo",
  "serve": "Serve",
  "description": "Descrição",
  "peoples_serves": "Serve quantas pessoas",
  "person": {
    "person": "pessoa",
    "people": "pessoas"
  },
  "difficulty_level": "Dificuldade",
  "difficulty_required": "Por favor, selecione um nível",
  "difficulty": {
    "easy": "fácil",
    "medium": "média",
    "hard": "difícil"
  },
  "recipe_type": {
    "breakfast": "café da manhã",
    "meal": "refeição",
    "side": "acompanhamento",
    "snack": "lanche",
    "drink": "bebida",
    "dessert": "sobremesa",
    "some_other": "outro"
  },
  "attention": "Atenção",
  "about": "Sobre",
  "backup": "Backup",
  "wish_leave": "Deseja sair sem salvar?",
  "sure_delete": "Tem certeza que deseja apagar essa receita?",
  "stay": "Ficar",
  "exit": "Sair",
  "yes": "Sim",
  "no": "Não",
  "unknow": "desconhecido",
  "not_informed": "não informado",
  "undefined": "indefinido",
  "save": "Salvar",
  "edit": "Editar",
  "delete": "Deletar",
  "search": "Buscar receitas...",
  "favorites": "Favoritos",
  "no_favorites_yet": "Nenhuma receita favorita ainda.\nToque no ícone de coração para adicionar!",
  "no_results_found": "Nenhuma receita encontrada para esta busca.",
  "sort_by": "Ordenar por",
  "sort_by_name": "Nome",
  "sort_by_type": "Tipo",
  "sort_by_difficulty": "Dificuldade",
  "prep_time": "Tempo de preparo",
  "prep_time_minutes": "{minutes} min",
  "prep_time_hint": "Tempo em minutos",
  "about_app_info": "Informações do App",
  "about_version": "Versão",
  "about_build": "Build",
  "about_package": "Pacote",
  "about_device_info": "Informações do Dispositivo",
  "about_device_model": "Modelo",
  "about_device_os": "Sistema Operacional",
  "about_device_os_version": "Versão do SO",
  "about_licenses": "Licenças de código aberto",
  "settings": "Configurações",
  "settings_theme_color": "Cor do tema",
  "settings_language": "Idioma"
};
static const Map<String,dynamic> _en = {
  "recipe": "Recipe",
  "my_recipe_book": "My recipe book",
  "recipe_book": "Recipe book",
  "recipe_title": "Title of the recipe",
  "new_recipe": "New recipe",
  "add_new_recipe": "Add new recipe",
  "no_recipe_add_yet": "No recipe add yet...",
  "ingredients": "Ingredients",
  "ingredient": {
    "full": "{quantity} {measure} of {name}",
    "partial": "{quantity} {fraction} {measure} of {name}"
  },
  "add_ingredient": "Add ingredient",
  "delete_ingredient": "Delete ingredient",
  "move_ingredient": "Move ingredient",
  "ingredient_hint": "e.g.: 100g sugar",
  "steps": "Steps",
  "add_step": "Add step",
  "delete_step": "Delete step",
  "move_step": "Move step",
  "title_required": "Please, enter with some title",
  "type": "Type",
  "type_required": "Please, select a type",
  "serve": "Serve",
  "description": "Description",
  "peoples_serves": "Serves how many people",
  "person": {
    "person": "person",
    "people": "people"
  },
  "difficulty_level": "Difficulty",
  "difficulty_required": "Please, select a level",
  "difficulty": {
    "easy": "easy",
    "medium": "medium",
    "hard": "hard"
  },
  "recipe_type": {
    "breakfast": "breakfast",
    "meal": "meal",
    "side": "side",
    "snack": "snack",
    "drink": "drink",
    "dessert": "dessert",
    "some_other": "other"
  },
  "attention": "Attention",
  "about": "About",
  "backup": "Backup",
  "wish_leave": "Wish leave withou save?",
  "sure_delete": "Are you sure you want to delete this recipe?",
  "stay": "Stay",
  "exit": "Exit",
  "yes": "Yes",
  "no": "No",
  "unknow": "unknow",
  "not_informed": "not informed",
  "undefined": "undefined",
  "save": "Save",
  "edit": "Edit",
  "delete": "Delete",
  "search": "Search recipes...",
  "favorites": "Favorites",
  "no_favorites_yet": "No favorite recipes yet.\nTap the heart icon to add one!",
  "no_results_found": "No recipes found for this search.",
  "sort_by": "Sort by",
  "sort_by_name": "Name",
  "sort_by_type": "Type",
  "sort_by_difficulty": "Difficulty",
  "prep_time": "Prep time",
  "prep_time_minutes": "{minutes} min",
  "prep_time_hint": "Time in minutes",
  "about_app_info": "App Info",
  "about_version": "Version",
  "about_build": "Build",
  "about_package": "Package",
  "about_device_info": "Device Info",
  "about_device_model": "Model",
  "about_device_os": "Operating System",
  "about_device_os_version": "OS Version",
  "about_licenses": "Open source licenses",
  "settings": "Settings",
  "settings_theme_color": "Theme color",
  "settings_language": "Language"
};
static const Map<String,dynamic> _it = {
  "recipe": "Ricetta",
  "my_recipe_book": "Il mio ricettario",
  "recipe_book": "Ricettario",
  "recipe_title": "Nome della ricetta",
  "new_recipe": "Nuova ricetta",
  "add_new_recipe": "Aggiungi nuova ricetta",
  "no_recipe_add_yet": "Nessuna ricetta aggiunta ancora...",
  "ingredients": "Ingredienti",
  "ingredient": {
    "full": "{quantity} {measure} di {name}",
    "partial": "{quantity} {fraction} {measure} di {name}"
  },
  "add_ingredient": "Aggiungi ingrediente",
  "delete_ingredient": "Elimina ingrediente",
  "move_ingredient": "Sposta ingrediente",
  "ingredient_hint": "es.: 100g di zucchero",
  "steps": "Preparazione",
  "add_step": "Aggiungi passaggio",
  "delete_step": "Elimina passaggio",
  "move_step": "Sposta passaggio",
  "title_required": "Per favore, inserisci un titolo",
  "type": "Tipo",
  "type_required": "Per favore, seleziona un tipo",
  "serve": "Porzioni",
  "description": "Descrizione",
  "peoples_serves": "Porzioni per quante persone",
  "person": {
    "person": "persona",
    "people": "persone"
  },
  "difficulty_level": "Difficoltà",
  "difficulty_required": "Per favore, seleziona un livello",
  "difficulty": {
    "easy": "facile",
    "medium": "media",
    "hard": "difficile"
  },
  "recipe_type": {
    "breakfast": "colazione",
    "meal": "pasto",
    "side": "contorno",
    "snack": "spuntino",
    "drink": "bevanda",
    "dessert": "dolce",
    "some_other": "altro"
  },
  "attention": "Attenzione",
  "about": "Informazioni",
  "backup": "Backup",
  "wish_leave": "Vuoi uscire senza salvare?",
  "sure_delete": "Sei sicuro di voler eliminare questa ricetta?",
  "stay": "Resta",
  "exit": "Esci",
  "yes": "Sì",
  "no": "No",
  "unknow": "sconosciuto",
  "not_informed": "non informato",
  "undefined": "indefinito",
  "save": "Salva",
  "edit": "Modifica",
  "delete": "Elimina",
  "search": "Cerca ricette...",
  "favorites": "Preferiti",
  "no_favorites_yet": "Nessuna ricetta preferita ancora.\nTocca l'icona del cuore per aggiungerne una!",
  "no_results_found": "Nessuna ricetta trovata per questa ricerca.",
  "sort_by": "Ordina per",
  "sort_by_name": "Nome",
  "sort_by_type": "Tipo",
  "sort_by_difficulty": "Difficoltà",
  "prep_time": "Tempo di preparazione",
  "prep_time_minutes": "{minutes} min",
  "prep_time_hint": "Tempo in minuti",
  "about_app_info": "Info sull'App",
  "about_version": "Versione",
  "about_build": "Build",
  "about_package": "Pacchetto",
  "about_device_info": "Info sul Dispositivo",
  "about_device_model": "Modello",
  "about_device_os": "Sistema Operativo",
  "about_device_os_version": "Versione SO",
  "about_licenses": "Licenze open source",
  "settings": "Impostazioni",
  "settings_theme_color": "Colore del tema",
  "settings_language": "Lingua"
};
static const Map<String,dynamic> _es = {
  "recipe": "Receta",
  "my_recipe_book": "Mi libro de recetas",
  "recipe_book": "Libro de recetas",
  "recipe_title": "Nombre de la receta",
  "new_recipe": "Nueva receta",
  "add_new_recipe": "Agregar nueva receta",
  "no_recipe_add_yet": "Ninguna receta agregada aún...",
  "ingredients": "Ingredientes",
  "ingredient": {
    "full": "{quantity} {measure} de {name}",
    "partial": "{quantity} {fraction} {measure} de {name}"
  },
  "add_ingredient": "Agregar ingrediente",
  "delete_ingredient": "Eliminar ingrediente",
  "move_ingredient": "Mover ingrediente",
  "ingredient_hint": "ej.: 100g de azúcar",
  "steps": "Preparación",
  "add_step": "Agregar paso",
  "delete_step": "Eliminar paso",
  "move_step": "Mover paso",
  "title_required": "Por favor, ingrese un título",
  "type": "Tipo",
  "type_required": "Por favor, seleccione un tipo",
  "serve": "Porciones",
  "description": "Descripción",
  "peoples_serves": "Porciones para cuántas personas",
  "person": {
    "person": "persona",
    "people": "personas"
  },
  "difficulty_level": "Dificultad",
  "difficulty_required": "Por favor, seleccione un nivel",
  "difficulty": {
    "easy": "fácil",
    "medium": "media",
    "hard": "difícil"
  },
  "recipe_type": {
    "breakfast": "desayuno",
    "meal": "comida",
    "side": "acompañamiento",
    "snack": "merienda",
    "drink": "bebida",
    "dessert": "postre",
    "some_other": "otro"
  },
  "attention": "Atención",
  "about": "Acerca de",
  "backup": "Respaldo",
  "wish_leave": "¿Desea salir sin guardar?",
  "sure_delete": "¿Está seguro de que desea eliminar esta receta?",
  "stay": "Quedarse",
  "exit": "Salir",
  "yes": "Sí",
  "no": "No",
  "unknow": "desconocido",
  "not_informed": "no informado",
  "undefined": "indefinido",
  "save": "Guardar",
  "edit": "Editar",
  "delete": "Eliminar",
  "search": "Buscar recetas...",
  "favorites": "Favoritos",
  "no_favorites_yet": "Aún no hay recetas favoritas.\n¡Toque el ícono de corazón para agregar una!",
  "no_results_found": "No se encontraron recetas para esta búsqueda.",
  "sort_by": "Ordenar por",
  "sort_by_name": "Nombre",
  "sort_by_type": "Tipo",
  "sort_by_difficulty": "Dificultad",
  "prep_time": "Tiempo de preparación",
  "prep_time_minutes": "{minutes} min",
  "prep_time_hint": "Tiempo en minutos",
  "about_app_info": "Información de la App",
  "about_version": "Versión",
  "about_build": "Build",
  "about_package": "Paquete",
  "about_device_info": "Información del Dispositivo",
  "about_device_model": "Modelo",
  "about_device_os": "Sistema Operativo",
  "about_device_os_version": "Versión del SO",
  "about_licenses": "Licencias de código abierto",
  "settings": "Configuración",
  "settings_theme_color": "Color del tema",
  "settings_language": "Idioma"
};
static const Map<String, Map<String,dynamic>> mapLocales = {"de": _de, "ru": _ru, "pt": _pt, "en": _en, "it": _it, "es": _es};
}
