// DO NOT EDIT. This is code generated via package:easy_localization/generate.dart

// ignore_for_file: prefer_single_quotes, avoid_renaming_method_parameters, constant_identifier_names

import 'dart:ui';

import 'package:easy_localization/easy_localization.dart' show AssetLoader;

class CodegenLoader extends AssetLoader{
  const CodegenLoader();

  @override
  Future<Map<String, dynamic>?> load(String path, Locale locale) {
    return Future.value(mapLocales[locale.toString()]);
  }

  static const Map<String,dynamic> _de = {
  "recipe": "Rezept",
  "my_recipe_book": "Mein Rezeptbuch",
  "recipe_book": "Rezeptbuch",
  "recipe_title": "Name des Rezepts",
  "new_recipe": "Neues Rezept",
  "add_new_recipe": "Neues Rezept hinzufügen",
  "no_recipe_add_yet": "Noch kein Rezept hinzugefügt...",
  "ingredients": "Zutaten",
  "ingredient": {
    "full": "{quantity} {measure} {name}",
    "partial": "{quantity} {fraction} {measure} {name}"
  },
  "add_ingredient": "Zutat hinzufügen",
  "delete_ingredient": "Zutat löschen",
  "move_ingredient": "Zutat verschieben",
  "ingredient_hint": "z.B.: 100g Zucker",
  "steps": "Zubereitung",
  "add_step": "Schritt hinzufügen",
  "delete_step": "Schritt löschen",
  "move_step": "Schritt verschieben",
  "title_required": "Bitte geben Sie einen Titel ein",
  "type": "Typ",
  "type_required": "Bitte wählen Sie einen Typ",
  "serve": "Portionen",
  "description": "Beschreibung",
  "peoples_serves": "Portionen für wie viele Personen",
  "person": {
    "person": "Person",
    "people": "Personen"
  },
  "difficulty_level": "Schwierigkeit",
  "difficulty_required": "Bitte wählen Sie ein Niveau",
  "difficulty": {
    "easy": "einfach",
    "medium": "mittel",
    "hard": "schwer"
  },
  "recipe_type": {
    "breakfast": "Frühstück",
    "meal": "Mahlzeit",
    "side": "Beilage",
    "snack": "Snack",
    "drink": "Getränk",
    "dessert": "Dessert",
    "some_other": "Sonstiges"
  },
  "attention": "Achtung",
  "about": "Über",
  "backup": "Sicherung",
  "wish_leave": "Möchten Sie ohne Speichern verlassen?",
  "sure_delete": "Sind Sie sicher, dass Sie dieses Rezept löschen möchten?",
  "stay": "Bleiben",
  "exit": "Verlassen",
  "yes": "Ja",
  "no": "Nein",
  "unknow": "unbekannt",
  "not_informed": "nicht angegeben",
  "undefined": "undefiniert",
  "save": "Speichern",
  "edit": "Bearbeiten",
  "delete": "Löschen",
  "search": "Rezepte suchen...",
  "favorites": "Favoriten",
  "no_favorites_yet": "Noch keine Lieblingsrezepte.\nTippen Sie auf das Herzsymbol, um eines hinzuzufügen!",
  "no_results_found": "Keine Rezepte für diese Suche gefunden.",
  "sort_by": "Sortieren nach",
  "sort_by_name": "Name",
  "sort_by_type": "Typ",
  "sort_by_difficulty": "Schwierigkeit",
  "prep_time": "Zubereitungszeit",
  "prep_time_minutes": "{minutes} Min.",
  "prep_time_hint": "Zeit in Minuten",
  "about_app_info": "App-Informationen",
  "about_version": "Version",
  "about_build": "Build",
  "about_package": "Paket",
  "about_device_info": "Geräteinformationen",
  "about_device_model": "Modell",
  "about_device_os": "Betriebssystem",
  "about_device_os_version": "BS-Version",
  "about_licenses": "Open-Source-Lizenzen",
  "settings": "Einstellungen",
  "settings_theme_color": "Themenfarbe",
  "settings_language": "Sprache",
  "share": "Teilen",
  "error_load_recipes": "Rezepte konnten nicht geladen werden. Bitte versuchen Sie es erneut.",
  "error_save_recipe": "Rezept konnte nicht gespeichert werden. Bitte versuchen Sie es erneut.",
  "error_generic": "Etwas ist schiefgelaufen. Bitte versuchen Sie es erneut.",
  "settings_dark_mode": "Erscheinungsbild",
  "settings_dark_mode_light": "Hell",
  "settings_dark_mode_dark": "Dunkel",
  "settings_dark_mode_system": "System",
  "settings_font_size": "Schriftgröße",
  "settings_font_small": "Klein",
  "settings_font_medium": "Mittel",
  "settings_font_large": "Groß",
  "settings_behavior": "Verhalten",
  "settings_default_sort": "Standard-Sortierung",
  "settings_confirm_delete": "Vor dem Löschen bestätigen",
  "settings_data": "Daten",
  "settings_export": "Rezepte exportieren",
  "settings_import": "Rezepte importieren",
  "settings_delete_all": "Alle Rezepte löschen",
  "settings_delete_all_confirm": "Dadurch werden alle Rezepte dauerhaft gelöscht. Sind Sie sicher?",
  "settings_export_success": "Rezepte erfolgreich exportiert!",
  "settings_import_success": "{count} Rezepte erfolgreich importiert!",
  "settings_delete_all_success": "Alle Rezepte wurden gelöscht.",
  "settings_import_hint": "Fügen Sie den exportierten JSON hier ein",
  "settings_export_description": "Speichern Sie Ihre Rezepte als JSON-Datei",
  "settings_import_description": "Rezepte aus einem JSON-Backup wiederherstellen",
  "settings_delete_all_description": "Alle Rezepte dauerhaft entfernen",
  "nps_title": "Deine Meinung zählt!",
  "nps_question": "Wie wahrscheinlich ist es, dass du diese App einem Freund empfiehlst?",
  "nps_not_likely": "Unwahrscheinlich",
  "nps_very_likely": "Sehr wahrscheinlich",
  "nps_submit": "Absenden",
  "nps_later": "Später",
  "nps_thanks": "Danke für dein Feedback!"
};
static const Map<String,dynamic> _ru = {
  "recipe": "Рецепт",
  "my_recipe_book": "Моя книга рецептов",
  "recipe_book": "Книга рецептов",
  "recipe_title": "Название рецепта",
  "new_recipe": "Новый рецепт",
  "add_new_recipe": "Добавить новый рецепт",
  "no_recipe_add_yet": "Рецептов пока нет...",
  "ingredients": "Ингредиенты",
  "ingredient": {
    "full": "{quantity} {measure} {name}",
    "partial": "{quantity} {fraction} {measure} {name}"
  },
  "add_ingredient": "Добавить ингредиент",
  "delete_ingredient": "Удалить ингредиент",
  "move_ingredient": "Переместить ингредиент",
  "ingredient_hint": "напр.: 100г сахара",
  "steps": "Приготовление",
  "add_step": "Добавить шаг",
  "delete_step": "Удалить шаг",
  "move_step": "Переместить шаг",
  "title_required": "Пожалуйста, введите название",
  "type": "Тип",
  "type_required": "Пожалуйста, выберите тип",
  "serve": "Порции",
  "description": "Описание",
  "peoples_serves": "Порций на сколько человек",
  "person": {
    "person": "человек",
    "people": "человек"
  },
  "difficulty_level": "Сложность",
  "difficulty_required": "Пожалуйста, выберите уровень",
  "difficulty": {
    "easy": "лёгкий",
    "medium": "средний",
    "hard": "сложный"
  },
  "recipe_type": {
    "breakfast": "завтрак",
    "meal": "основное блюдо",
    "side": "гарнир",
    "snack": "перекус",
    "drink": "напиток",
    "dessert": "десерт",
    "some_other": "другое"
  },
  "attention": "Внимание",
  "about": "О приложении",
  "backup": "Резервная копия",
  "wish_leave": "Хотите выйти без сохранения?",
  "sure_delete": "Вы уверены, что хотите удалить этот рецепт?",
  "stay": "Остаться",
  "exit": "Выйти",
  "yes": "Да",
  "no": "Нет",
  "unknow": "неизвестно",
  "not_informed": "не указано",
  "undefined": "не определено",
  "save": "Сохранить",
  "edit": "Редактировать",
  "delete": "Удалить",
  "search": "Поиск рецептов...",
  "favorites": "Избранное",
  "no_favorites_yet": "Избранных рецептов пока нет.\nНажмите на значок сердца, чтобы добавить!",
  "no_results_found": "Рецепты по этому запросу не найдены.",
  "sort_by": "Сортировать по",
  "sort_by_name": "Название",
  "sort_by_type": "Тип",
  "sort_by_difficulty": "Сложность",
  "prep_time": "Время приготовления",
  "prep_time_minutes": "{minutes} мин.",
  "prep_time_hint": "Время в минутах",
  "about_app_info": "Информация о приложении",
  "about_version": "Версия",
  "about_build": "Сборка",
  "about_package": "Пакет",
  "about_device_info": "Информация об устройстве",
  "about_device_model": "Модель",
  "about_device_os": "Операционная система",
  "about_device_os_version": "Версия ОС",
  "about_licenses": "Лицензии открытого кода",
  "settings": "Настройки",
  "settings_theme_color": "Цвет темы",
  "settings_language": "Язык",
  "share": "Поделиться",
  "error_load_recipes": "Не удалось загрузить рецепты. Попробуйте ещё раз.",
  "error_save_recipe": "Не удалось сохранить рецепт. Попробуйте ещё раз.",
  "error_generic": "Что-то пошло не так. Попробуйте ещё раз.",
  "settings_dark_mode": "Оформление",
  "settings_dark_mode_light": "Светлая",
  "settings_dark_mode_dark": "Тёмная",
  "settings_dark_mode_system": "Системная",
  "settings_font_size": "Размер шрифта",
  "settings_font_small": "Маленький",
  "settings_font_medium": "Средний",
  "settings_font_large": "Большой",
  "settings_behavior": "Поведение",
  "settings_default_sort": "Сортировка по умолчанию",
  "settings_confirm_delete": "Подтверждать перед удалением",
  "settings_data": "Данные",
  "settings_export": "Экспорт рецептов",
  "settings_import": "Импорт рецептов",
  "settings_delete_all": "Удалить все рецепты",
  "settings_delete_all_confirm": "Это навсегда удалит все рецепты. Вы уверены?",
  "settings_export_success": "Рецепты успешно экспортированы!",
  "settings_import_success": "{count} рецептов успешно импортировано!",
  "settings_delete_all_success": "Все рецепты удалены.",
  "settings_import_hint": "Вставьте экспортированный JSON сюда",
  "settings_export_description": "Сохраните рецепты в файл JSON",
  "settings_import_description": "Восстановите рецепты из резервной копии JSON",
  "settings_delete_all_description": "Безвозвратно удалить все рецепты",
  "nps_title": "Ваше мнение важно!",
  "nps_question": "Насколько вероятно, что вы порекомендуете это приложение другу?",
  "nps_not_likely": "Маловероятно",
  "nps_very_likely": "Очень вероятно",
  "nps_submit": "Отправить",
  "nps_later": "Позже",
  "nps_thanks": "Спасибо за ваш отзыв!"
};
static const Map<String,dynamic> _pt = {
  "recipe": "Receita",
  "my_recipe_book": "Meu livro de receitas",
  "recipe_book": "Livro de receitas",
  "recipe_title": "Nome da receita",
  "new_recipe": "Nova receita",
  "add_new_recipe": "Adicionar nova receita",
  "no_recipe_add_yet": "Nenhuma receita adiciona ainda...",
  "ingredients": "Ingredientes",
  "ingredient": {
    "full": "{quantity} {measure} de {name}",
    "partial": "{quantity} {fraction} {measure} de {name}"
  },
  "add_ingredient": "Adicionar ingrediente",
  "delete_ingredient": "Excluir ingrediente",
  "move_ingredient": "Mover ingrediente",
  "ingredient_hint": "ex.: 100g de açúcar",
  "steps": "Modo de preparo",
  "add_step": "Adicionar passo",
  "delete_step": "Excluir passo",
  "move_step": "Mover passo",
  "title_required": "Por favor, informe um título",
  "type": "Tipo",
  "type_required": "Por favor, selecione um tipo",
  "serve": "Serve",
  "description": "Descrição",
  "peoples_serves": "Serve quantas pessoas",
  "person": {
    "person": "pessoa",
    "people": "pessoas"
  },
  "difficulty_level": "Dificuldade",
  "difficulty_required": "Por favor, selecione um nível",
  "difficulty": {
    "easy": "fácil",
    "medium": "média",
    "hard": "difícil"
  },
  "recipe_type": {
    "breakfast": "café da manhã",
    "meal": "refeição",
    "side": "acompanhamento",
    "snack": "lanche",
    "drink": "bebida",
    "dessert": "sobremesa",
    "some_other": "outro"
  },
  "attention": "Atenção",
  "about": "Sobre",
  "backup": "Backup",
  "wish_leave": "Deseja sair sem salvar?",
  "sure_delete": "Tem certeza que deseja apagar essa receita?",
  "stay": "Ficar",
  "exit": "Sair",
  "yes": "Sim",
  "no": "Não",
  "unknow": "desconhecido",
  "not_informed": "não informado",
  "undefined": "indefinido",
  "save": "Salvar",
  "edit": "Editar",
  "delete": "Deletar",
  "search": "Buscar receitas...",
  "favorites": "Favoritos",
  "no_favorites_yet": "Nenhuma receita favorita ainda.\nToque no ícone de coração para adicionar!",
  "no_results_found": "Nenhuma receita encontrada para esta busca.",
  "sort_by": "Ordenar por",
  "sort_by_name": "Nome",
  "sort_by_type": "Tipo",
  "sort_by_difficulty": "Dificuldade",
  "prep_time": "Tempo de preparo",
  "prep_time_minutes": "{minutes} min",
  "prep_time_hint": "Tempo em minutos",
  "about_app_info": "Informações do App",
  "about_version": "Versão",
  "about_build": "Build",
  "about_package": "Pacote",
  "about_device_info": "Informações do Dispositivo",
  "about_device_model": "Modelo",
  "about_device_os": "Sistema Operacional",
  "about_device_os_version": "Versão do SO",
  "about_licenses": "Licenças de código aberto",
  "settings": "Configurações",
  "settings_theme_color": "Cor do tema",
  "settings_language": "Idioma",
  "share": "Compartilhar",
  "error_load_recipes": "Falha ao carregar receitas. Tente novamente.",
  "error_save_recipe": "Falha ao salvar receita. Tente novamente.",
  "error_generic": "Algo deu errado. Tente novamente.",
  "settings_dark_mode": "Aparência",
  "settings_dark_mode_light": "Claro",
  "settings_dark_mode_dark": "Escuro",
  "settings_dark_mode_system": "Sistema",
  "settings_font_size": "Tamanho da fonte",
  "settings_font_small": "Pequeno",
  "settings_font_medium": "Médio",
  "settings_font_large": "Grande",
  "settings_behavior": "Comportamento",
  "settings_default_sort": "Ordenação padrão",
  "settings_confirm_delete": "Confirmar antes de deletar",
  "settings_data": "Dados",
  "settings_export": "Exportar receitas",
  "settings_import": "Importar receitas",
  "settings_delete_all": "Apagar todas as receitas",
  "settings_delete_all_confirm": "Isso apagará permanentemente todas as receitas. Tem certeza?",
  "settings_export_success": "Receitas exportadas com sucesso!",
  "settings_import_success": "{count} receitas importadas com sucesso!",
  "settings_delete_all_success": "Todas as receitas foram apagadas.",
  "settings_import_hint": "Cole o JSON exportado aqui",
  "settings_export_description": "Salve suas receitas como arquivo JSON",
  "settings_import_description": "Restaure receitas de um backup JSON",
  "settings_delete_all_description": "Remova permanentemente todas as receitas",
  "nps_title": "Sua opinião importa!",
  "nps_question": "Qual a probabilidade de você recomendar este app a um amigo?",
  "nps_not_likely": "Pouco provável",
  "nps_very_likely": "Muito provável",
  "nps_submit": "Enviar",
  "nps_later": "Depois",
  "nps_thanks": "Obrigado pelo seu feedback!"
};
static const Map<String,dynamic> _en = {
  "recipe": "Recipe",
  "my_recipe_book": "My recipe book",
  "recipe_book": "Recipe book",
  "recipe_title": "Title of the recipe",
  "new_recipe": "New recipe",
  "add_new_recipe": "Add new recipe",
  "no_recipe_add_yet": "No recipe add yet...",
  "ingredients": "Ingredients",
  "ingredient": {
    "full": "{quantity} {measure} of {name}",
    "partial": "{quantity} {fraction} {measure} of {name}"
  },
  "add_ingredient": "Add ingredient",
  "delete_ingredient": "Delete ingredient",
  "move_ingredient": "Move ingredient",
  "ingredient_hint": "e.g.: 100g sugar",
  "steps": "Steps",
  "add_step": "Add step",
  "delete_step": "Delete step",
  "move_step": "Move step",
  "title_required": "Please, enter with some title",
  "type": "Type",
  "type_required": "Please, select a type",
  "serve": "Serve",
  "description": "Description",
  "peoples_serves": "Serves how many people",
  "person": {
    "person": "person",
    "people": "people"
  },
  "difficulty_level": "Difficulty",
  "difficulty_required": "Please, select a level",
  "difficulty": {
    "easy": "easy",
    "medium": "medium",
    "hard": "hard"
  },
  "recipe_type": {
    "breakfast": "breakfast",
    "meal": "meal",
    "side": "side",
    "snack": "snack",
    "drink": "drink",
    "dessert": "dessert",
    "some_other": "other"
  },
  "attention": "Attention",
  "about": "About",
  "backup": "Backup",
  "wish_leave": "Wish leave withou save?",
  "sure_delete": "Are you sure you want to delete this recipe?",
  "stay": "Stay",
  "exit": "Exit",
  "yes": "Yes",
  "no": "No",
  "unknow": "unknow",
  "not_informed": "not informed",
  "undefined": "undefined",
  "save": "Save",
  "edit": "Edit",
  "delete": "Delete",
  "search": "Search recipes...",
  "favorites": "Favorites",
  "no_favorites_yet": "No favorite recipes yet.\nTap the heart icon to add one!",
  "no_results_found": "No recipes found for this search.",
  "sort_by": "Sort by",
  "sort_by_name": "Name",
  "sort_by_type": "Type",
  "sort_by_difficulty": "Difficulty",
  "prep_time": "Prep time",
  "prep_time_minutes": "{minutes} min",
  "prep_time_hint": "Time in minutes",
  "about_app_info": "App Info",
  "about_version": "Version",
  "about_build": "Build",
  "about_package": "Package",
  "about_device_info": "Device Info",
  "about_device_model": "Model",
  "about_device_os": "Operating System",
  "about_device_os_version": "OS Version",
  "about_licenses": "Open source licenses",
  "settings": "Settings",
  "settings_theme_color": "Theme color",
  "settings_language": "Language",
  "share": "Share",
  "error_load_recipes": "Failed to load recipes. Please try again.",
  "error_save_recipe": "Failed to save recipe. Please try again.",
  "error_generic": "Something went wrong. Please try again.",
  "settings_dark_mode": "Appearance",
  "settings_dark_mode_light": "Light",
  "settings_dark_mode_dark": "Dark",
  "settings_dark_mode_system": "System",
  "settings_font_size": "Font size",
  "settings_font_small": "Small",
  "settings_font_medium": "Medium",
  "settings_font_large": "Large",
  "settings_behavior": "Behavior",
  "settings_default_sort": "Default sort order",
  "settings_confirm_delete": "Confirm before deleting",
  "settings_data": "Data",
  "settings_export": "Export recipes",
  "settings_import": "Import recipes",
  "settings_delete_all": "Delete all recipes",
  "settings_delete_all_confirm": "This will permanently delete all recipes. Are you sure?",
  "settings_export_success": "Recipes exported successfully!",
  "settings_import_success": "{count} recipes imported successfully!",
  "settings_delete_all_success": "All recipes deleted.",
  "settings_import_hint": "Paste the exported JSON here",
  "settings_export_description": "Save your recipes as a JSON file",
  "settings_import_description": "Restore recipes from a JSON backup",
  "settings_delete_all_description": "Permanently remove all recipes",
  "nps_title": "Your opinion matters!",
  "nps_question": "How likely are you to recommend this app to a friend?",
  "nps_not_likely": "Not likely",
  "nps_very_likely": "Very likely",
  "nps_submit": "Submit",
  "nps_later": "Later",
  "nps_thanks": "Thank you for your feedback!"
};
static const Map<String,dynamic> _it = {
  "recipe": "Ricetta",
  "my_recipe_book": "Il mio ricettario",
  "recipe_book": "Ricettario",
  "recipe_title": "Nome della ricetta",
  "new_recipe": "Nuova ricetta",
  "add_new_recipe": "Aggiungi nuova ricetta",
  "no_recipe_add_yet": "Nessuna ricetta aggiunta ancora...",
  "ingredients": "Ingredienti",
  "ingredient": {
    "full": "{quantity} {measure} di {name}",
    "partial": "{quantity} {fraction} {measure} di {name}"
  },
  "add_ingredient": "Aggiungi ingrediente",
  "delete_ingredient": "Elimina ingrediente",
  "move_ingredient": "Sposta ingrediente",
  "ingredient_hint": "es.: 100g di zucchero",
  "steps": "Preparazione",
  "add_step": "Aggiungi passaggio",
  "delete_step": "Elimina passaggio",
  "move_step": "Sposta passaggio",
  "title_required": "Per favore, inserisci un titolo",
  "type": "Tipo",
  "type_required": "Per favore, seleziona un tipo",
  "serve": "Porzioni",
  "description": "Descrizione",
  "peoples_serves": "Porzioni per quante persone",
  "person": {
    "person": "persona",
    "people": "persone"
  },
  "difficulty_level": "Difficoltà",
  "difficulty_required": "Per favore, seleziona un livello",
  "difficulty": {
    "easy": "facile",
    "medium": "media",
    "hard": "difficile"
  },
  "recipe_type": {
    "breakfast": "colazione",
    "meal": "pasto",
    "side": "contorno",
    "snack": "spuntino",
    "drink": "bevanda",
    "dessert": "dolce",
    "some_other": "altro"
  },
  "attention": "Attenzione",
  "about": "Informazioni",
  "backup": "Backup",
  "wish_leave": "Vuoi uscire senza salvare?",
  "sure_delete": "Sei sicuro di voler eliminare questa ricetta?",
  "stay": "Resta",
  "exit": "Esci",
  "yes": "Sì",
  "no": "No",
  "unknow": "sconosciuto",
  "not_informed": "non informato",
  "undefined": "indefinito",
  "save": "Salva",
  "edit": "Modifica",
  "delete": "Elimina",
  "search": "Cerca ricette...",
  "favorites": "Preferiti",
  "no_favorites_yet": "Nessuna ricetta preferita ancora.\nTocca l'icona del cuore per aggiungerne una!",
  "no_results_found": "Nessuna ricetta trovata per questa ricerca.",
  "sort_by": "Ordina per",
  "sort_by_name": "Nome",
  "sort_by_type": "Tipo",
  "sort_by_difficulty": "Difficoltà",
  "prep_time": "Tempo di preparazione",
  "prep_time_minutes": "{minutes} min",
  "prep_time_hint": "Tempo in minuti",
  "about_app_info": "Info sull'App",
  "about_version": "Versione",
  "about_build": "Build",
  "about_package": "Pacchetto",
  "about_device_info": "Info sul Dispositivo",
  "about_device_model": "Modello",
  "about_device_os": "Sistema Operativo",
  "about_device_os_version": "Versione SO",
  "about_licenses": "Licenze open source",
  "settings": "Impostazioni",
  "settings_theme_color": "Colore del tema",
  "settings_language": "Lingua",
  "share": "Condividi",
  "error_load_recipes": "Impossibile caricare le ricette. Riprova.",
  "error_save_recipe": "Impossibile salvare la ricetta. Riprova.",
  "error_generic": "Qualcosa è andato storto. Riprova.",
  "settings_dark_mode": "Aspetto",
  "settings_dark_mode_light": "Chiaro",
  "settings_dark_mode_dark": "Scuro",
  "settings_dark_mode_system": "Sistema",
  "settings_font_size": "Dimensione del testo",
  "settings_font_small": "Piccolo",
  "settings_font_medium": "Medio",
  "settings_font_large": "Grande",
  "settings_behavior": "Comportamento",
  "settings_default_sort": "Ordinamento predefinito",
  "settings_confirm_delete": "Conferma prima di eliminare",
  "settings_data": "Dati",
  "settings_export": "Esporta ricette",
  "settings_import": "Importa ricette",
  "settings_delete_all": "Elimina tutte le ricette",
  "settings_delete_all_confirm": "Questo eliminerà permanentemente tutte le ricette. Sei sicuro?",
  "settings_export_success": "Ricette esportate con successo!",
  "settings_import_success": "{count} ricette importate con successo!",
  "settings_delete_all_success": "Tutte le ricette sono state eliminate.",
  "settings_import_hint": "Incolla il JSON esportato qui",
  "settings_export_description": "Salva le tue ricette come file JSON",
  "settings_import_description": "Ripristina le ricette da un backup JSON",
  "settings_delete_all_description": "Rimuovi permanentemente tutte le ricette",
  "nps_title": "La tua opinione conta!",
  "nps_question": "Quanto è probabile che consigli questa app a un amico?",
  "nps_not_likely": "Poco probabile",
  "nps_very_likely": "Molto probabile",
  "nps_submit": "Invia",
  "nps_later": "Dopo",
  "nps_thanks": "Grazie per il tuo feedback!"
};
static const Map<String,dynamic> _es = {
  "recipe": "Receta",
  "my_recipe_book": "Mi libro de recetas",
  "recipe_book": "Libro de recetas",
  "recipe_title": "Nombre de la receta",
  "new_recipe": "Nueva receta",
  "add_new_recipe": "Agregar nueva receta",
  "no_recipe_add_yet": "Ninguna receta agregada aún...",
  "ingredients": "Ingredientes",
  "ingredient": {
    "full": "{quantity} {measure} de {name}",
    "partial": "{quantity} {fraction} {measure} de {name}"
  },
  "add_ingredient": "Agregar ingrediente",
  "delete_ingredient": "Eliminar ingrediente",
  "move_ingredient": "Mover ingrediente",
  "ingredient_hint": "ej.: 100g de azúcar",
  "steps": "Preparación",
  "add_step": "Agregar paso",
  "delete_step": "Eliminar paso",
  "move_step": "Mover paso",
  "title_required": "Por favor, ingrese un título",
  "type": "Tipo",
  "type_required": "Por favor, seleccione un tipo",
  "serve": "Porciones",
  "description": "Descripción",
  "peoples_serves": "Porciones para cuántas personas",
  "person": {
    "person": "persona",
    "people": "personas"
  },
  "difficulty_level": "Dificultad",
  "difficulty_required": "Por favor, seleccione un nivel",
  "difficulty": {
    "easy": "fácil",
    "medium": "media",
    "hard": "difícil"
  },
  "recipe_type": {
    "breakfast": "desayuno",
    "meal": "comida",
    "side": "acompañamiento",
    "snack": "merienda",
    "drink": "bebida",
    "dessert": "postre",
    "some_other": "otro"
  },
  "attention": "Atención",
  "about": "Acerca de",
  "backup": "Respaldo",
  "wish_leave": "¿Desea salir sin guardar?",
  "sure_delete": "¿Está seguro de que desea eliminar esta receta?",
  "stay": "Quedarse",
  "exit": "Salir",
  "yes": "Sí",
  "no": "No",
  "unknow": "desconocido",
  "not_informed": "no informado",
  "undefined": "indefinido",
  "save": "Guardar",
  "edit": "Editar",
  "delete": "Eliminar",
  "search": "Buscar recetas...",
  "favorites": "Favoritos",
  "no_favorites_yet": "Aún no hay recetas favoritas.\n¡Toque el ícono de corazón para agregar una!",
  "no_results_found": "No se encontraron recetas para esta búsqueda.",
  "sort_by": "Ordenar por",
  "sort_by_name": "Nombre",
  "sort_by_type": "Tipo",
  "sort_by_difficulty": "Dificultad",
  "prep_time": "Tiempo de preparación",
  "prep_time_minutes": "{minutes} min",
  "prep_time_hint": "Tiempo en minutos",
  "about_app_info": "Información de la App",
  "about_version": "Versión",
  "about_build": "Build",
  "about_package": "Paquete",
  "about_device_info": "Información del Dispositivo",
  "about_device_model": "Modelo",
  "about_device_os": "Sistema Operativo",
  "about_device_os_version": "Versión del SO",
  "about_licenses": "Licencias de código abierto",
  "settings": "Configuración",
  "settings_theme_color": "Color del tema",
  "settings_language": "Idioma",
  "share": "Compartir",
  "error_load_recipes": "Error al cargar las recetas. Inténtelo de nuevo.",
  "error_save_recipe": "Error al guardar la receta. Inténtelo de nuevo.",
  "error_generic": "Algo salió mal. Inténtelo de nuevo.",
  "settings_dark_mode": "Apariencia",
  "settings_dark_mode_light": "Claro",
  "settings_dark_mode_dark": "Oscuro",
  "settings_dark_mode_system": "Sistema",
  "settings_font_size": "Tamaño de fuente",
  "settings_font_small": "Pequeño",
  "settings_font_medium": "Mediano",
  "settings_font_large": "Grande",
  "settings_behavior": "Comportamiento",
  "settings_default_sort": "Orden predeterminado",
  "settings_confirm_delete": "Confirmar antes de eliminar",
  "settings_data": "Datos",
  "settings_export": "Exportar recetas",
  "settings_import": "Importar recetas",
  "settings_delete_all": "Eliminar todas las recetas",
  "settings_delete_all_confirm": "Esto eliminará permanentemente todas las recetas. ¿Está seguro?",
  "settings_export_success": "¡Recetas exportadas exitosamente!",
  "settings_import_success": "¡{count} recetas importadas exitosamente!",
  "settings_delete_all_success": "Todas las recetas fueron eliminadas.",
  "settings_import_hint": "Pegue el JSON exportado aquí",
  "settings_export_description": "Guarde sus recetas como archivo JSON",
  "settings_import_description": "Restaure recetas de un respaldo JSON",
  "settings_delete_all_description": "Elimine permanentemente todas las recetas",
  "nps_title": "¡Tu opinión importa!",
  "nps_question": "¿Qué tan probable es que recomiendes esta app a un amigo?",
  "nps_not_likely": "Poco probable",
  "nps_very_likely": "Muy probable",
  "nps_submit": "Enviar",
  "nps_later": "Después",
  "nps_thanks": "Gracias por tu comentario!"
};
static const Map<String, Map<String,dynamic>> mapLocales = {"de": _de, "ru": _ru, "pt": _pt, "en": _en, "it": _it, "es": _es};
}
